# Build Stage
FROM golang:1.22-alpine AS builder

WORKDIR /app

# Dependencies cachen
COPY go.mod go.sum ./
RUN go mod download

# Source kopieren und bauen
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -o operator ./cmd/operator

# Runtime Stage
FROM gcr.io/distroless/static:nonroot

WORKDIR /

COPY --from=builder /app/operator .

USER 65532:65532

ENTRYPOINT ["/operator"]
